// // This file was generated by Prisma, and assumes you have installed the following:
// // npm install --save-dev prisma dotenv
import 'dotenv/config';
// import { defineConfig } from "prisma/config";

// export default defineConfig({
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     url: process.env["DATABASE_URL"],
//   },
// });
// Remove imports that might cause loading issues in CJS
// import { defineConfig } from "prisma/config";

// Use a plain object export.
// TypeScript will still validate it if you use 'as const' or just trust the structure.

// prisma.config.ts
import { defineConfig } from 'prisma/config';

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // Docker Compose is injecting this into the air, so process.env will find it!
    url:
      process.env.DATABASE_URL ||
      'postgresql://opaline:youkai@localhost:5433/patchydb',
  },
});

// const config = {
//   schema: "prisma/schema.prisma",
//   migrations: {
//     path: "prisma/migrations",
//   },
//   datasource: {
//     // Access process.env directly
//     url: process.env.DATABASE_URL,
//   },
// };

// export default config;
